Layout
Linomadim/Modern-Todo pull request #2
Opened 2022-12-24 11:43 UTC by Linomadim

2022-12-24 12:21 UTC, Linomadim commented
![скрин, линтер без ошибок](https://user-images.githubusercontent.com/95148508/209435360-a8fafb74-6fe8-4b70-850f-13deceacfca4.png)
![screenshot layout(1440px)](https://user-images.githubusercontent.com/95148508/209436080-38204dff-4c3a-49c4-9b96-fffd14abea22.png)
![screenshot layout(768px)](https://user-images.githubusercontent.com/95148508/209436058-162f6a6a-8902-4b32-b81e-cafd5dc09384.png)

2023-01-15 13:57 UTC, Linomadim commented
![not error](https://user-images.githubusercontent.com/95148508/212544822-84494a6f-2df6-4149-b166-c032119f26fb.png)

Warning который тут на скрине показан не влияет на работу самого линта.

2023-01-15 14:05 UTC, Linomadim commented
![example](https://user-images.githubusercontent.com/95148508/212545390-acb61925-03c0-4fa7-a5c4-5a4133df58bc.png)

это запустил специально с ошибкой

2023-01-21 15:37 UTC, iihanchar requested changes

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.css
> +
Много лишних пустых строк. Линтер по хорошему должен был ругнуться тут

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.css
> +
лишняя пустая строка

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.js
> +const Icons = {
Создай src/utils/icons.js и вынеси туда. А потом будешь импортировать Icons везде, где тебе это нужно

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.js
> +
Если Modern Todo у тебя в приложении "точка входа", то есть самый верхний компонент, назови файл index.js или App.js
Все компоненты, классы и связанные с ними файлы, такие как css, группируй по папкам.
Что то вроде такого.
Плюс в именах файлов не используй пробелы
![image](https://user-images.githubusercontent.com/22117432/213873320-fca26553-0798-4bc0-b416-4a497fb10fc4.png)

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.js
> +const CategoriesObj = [
Если переменная хранит данные - с маленькой буквы, camelCase
Если переменная хранит константу, к примеру цвет, тип, или подобное - в UPPERCASE
Здесь у тебя данные

2023-01-21 15:37 UTC, iihanchar commented on src/Modern Todo.html
> +        </div>;
Не хватает одного </div>

2023-02-20 19:21 UTC, iihanchar commented on src/index.html
> +        </div>;
`;`

2023-02-20 19:21 UTC, iihanchar commented on src/index.html
> +    <div id="root">
не закрыт этот тег

2023-02-20 19:24 UTC, iihanchar approved these changes

2023-03-04 13:49 UTC, merged